name: CI

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npx playwright install --with-deps
      # sobe o app e roda os testes (playwright.config.ts já inicia o server)
      - run: PLAYWRIGHT_BASE_URL=http://127.0.0.1:3000 npx playwright test --reporter=html
      # salva relatório
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
      # sanity checks opcionais nas rotas/health
      - name: Health checks
        run: |
          curl -sSf http://127.0.0.1:3000/api/health | jq .
          curl -sSI http://127.0.0.1:3000/ | head -n 10
