name: CI

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci
      - run: npm run lint
      - run: npm run build

      # Playwright: browsers e libs de SO necessárias
      - run: npx playwright install --with-deps

      # Executa E2E; o webServer é controlado pelo playwright.config.ts
      - run: PLAYWRIGHT_BASE_URL=http://127.0.0.1:3000 npx playwright test --reporter=html

      # Artefacto principal: relatório HTML do Playwright
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: error
          retention-days: 14

      # Artefacto opcional: resultados brutos, se existirem
      - name: Upload test-results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: ignore
          retention-days: 7
